## download BRCA clinical survival records

In [1]:
!wget https://tcga-xena-hub.s3.us-east-1.amazonaws.com/download/survival/BRCA_survival.txt

--2026-02-18 10:54:35--  https://tcga-xena-hub.s3.us-east-1.amazonaws.com/download/survival/BRCA_survival.txt
Resolving tcga-xena-hub.s3.us-east-1.amazonaws.com (tcga-xena-hub.s3.us-east-1.amazonaws.com)... 16.15.216.81, 52.217.45.240, 52.216.60.122, ...
Connecting to tcga-xena-hub.s3.us-east-1.amazonaws.com (tcga-xena-hub.s3.us-east-1.amazonaws.com)|16.15.216.81|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 67919 (66K) [text/plain]
Saving to: ‘BRCA_survival.txt’

BRCA_survival.txt   100%[===================>]  66.33K  --.-KB/s    in 0.03s

2026-02-18 10:54:35 (2.43 MB/s) - ‘BRCA_survival.txt’ saved [67919/67919]

In [2]:
!ls

 brca_metabric_clinical_data.tsv
 BRCA_survival.txt
 drive
 metabric_embeddings.csv
 sample_data
'Supplementary Material S4_Eigengene_TCGA-BRCA.csv'
 tcga_embeddings.csv

In [3]:
import pandas as pd

survival = pd.read_csv("BRCA_survival.txt", sep="\t", index_col=0)

survival.head()

,_PATIENT,OS,OS.time,DSS,DSS.time,DFI,DFI.time,PFI,PFI.time,Redaction
sample,,,,,,,,,,
TCGA-3C-AAAU-01,TCGA-3C-AAAU,0,4047.0,0.0,4047.0,1.0,1808.0,1,1808.0,NaN
TCGA-3C-AALI-01,TCGA-3C-AALI,0,4005.0,0.0,4005.0,0.0,4005.0,0,4005.0,NaN
TCGA-3C-AALJ-01,TCGA-3C-AALJ,0,1474.0,0.0,1474.0,0.0,1474.0,0,1474.0,NaN
TCGA-3C-AALK-01,TCGA-3C-AALK,0,1448.0,0.0,1448.0,NaN,NaN,0,1448.0,NaN
TCGA-4H-AAAK-01,TCGA-4H-AAAK,0,348.0,0.0,348.0,0.0,348.0,0,348.0,NaN

In [4]:
survival = survival.set_index("_PATIENT")

survival = survival[["OS", "OS.time"]]

survival.head()

              OS  OS.time
_PATIENT
TCGA-3C-AAAU   0   4047.0
TCGA-3C-AALI   0   4005.0
TCGA-3C-AALJ   0   1474.0
TCGA-3C-AALK   0   1448.0
TCGA-4H-AAAK   0    348.0

## TGCA embeddings

In [5]:
import pandas as pd

# Load TCGA embeddings
tcga_emb = pd.read_csv('/content/tcga_embeddings.csv')

print("TCGA embeddings shape:", tcga_emb.shape)
tcga_emb.head()

TCGA embeddings shape: (1076, 26)

,patient_id,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,emb_7,emb_8,...,emb_15,emb_16,emb_17,emb_18,emb_19,emb_20,emb_21,emb_22,emb_23,cohort
0,TCGA-3C-AAAU,-0.030854,-0.135146,-0.041893,0.385757,-0.154153,0.699111,-0.245105,-0.036560,0.079290,...,0.076129,0.146797,-0.170391,0.156045,-0.431017,-0.257789,-0.452135,-0.035107,-0.233953,TCGA
1,TCGA-3C-AALI,1.262898,0.228456,-0.129620,0.682158,0.574874,-0.307807,0.134975,1.127026,-0.244317,...,0.772883,0.160773,0.498251,0.396043,0.597026,1.167793,-0.123010,0.381318,-0.535084,TCGA
2,TCGA-3C-AALJ,-0.427454,-0.316390,0.140457,-0.069793,-0.629212,-0.700468,0.208713,-0.192221,0.146112,...,-0.061963,0.258550,-0.417900,0.345478,0.442955,0.775435,-0.080222,0.283166,-0.026528,TCGA
3,TCGA-3C-AALK,-0.150010,0.204944,0.315294,0.160195,-0.067895,-0.270045,-0.004797,0.618876,-0.345056,...,-0.031831,0.348612,-0.354943,0.486604,0.151455,-0.517390,0.059857,0.228941,-0.356924,TCGA
4,TCGA-4H-AAAK,-0.080052,0.130887,-0.030450,0.350385,0.060477,-0.088916,-0.318143,0.179307,-0.577375,...,0.561928,0.106048,0.508212,-0.421759,0.367758,0.417073,0.544952,-0.148332,-0.206994,TCGA

In [6]:
# Load survival
survival = pd.read_csv("BRCA_survival.txt", sep="\t", index_col=0)

# Set proper patient ID
survival = survival.set_index("_PATIENT")

# Keep only OS and OS.time
survival = survival[["OS", "OS.time"]]

# Remove duplicates
survival = survival[~survival.index.duplicated(keep='first')]

print("Survival shape:", survival.shape)
survival.head()

Survival shape: (1097, 2)

              OS  OS.time
_PATIENT
TCGA-3C-AAAU   0   4047.0
TCGA-3C-AALI   0   4005.0
TCGA-3C-AALJ   0   1474.0
TCGA-3C-AALK   0   1448.0
TCGA-4H-AAAK   0    348.0

In [7]:
print("TCGA embedding shape:", tcga_emb.shape)
tcga_emb.head()

TCGA embedding shape: (1076, 26)

,patient_id,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,emb_7,emb_8,...,emb_15,emb_16,emb_17,emb_18,emb_19,emb_20,emb_21,emb_22,emb_23,cohort
0,TCGA-3C-AAAU,-0.030854,-0.135146,-0.041893,0.385757,-0.154153,0.699111,-0.245105,-0.036560,0.079290,...,0.076129,0.146797,-0.170391,0.156045,-0.431017,-0.257789,-0.452135,-0.035107,-0.233953,TCGA
1,TCGA-3C-AALI,1.262898,0.228456,-0.129620,0.682158,0.574874,-0.307807,0.134975,1.127026,-0.244317,...,0.772883,0.160773,0.498251,0.396043,0.597026,1.167793,-0.123010,0.381318,-0.535084,TCGA
2,TCGA-3C-AALJ,-0.427454,-0.316390,0.140457,-0.069793,-0.629212,-0.700468,0.208713,-0.192221,0.146112,...,-0.061963,0.258550,-0.417900,0.345478,0.442955,0.775435,-0.080222,0.283166,-0.026528,TCGA
3,TCGA-3C-AALK,-0.150010,0.204944,0.315294,0.160195,-0.067895,-0.270045,-0.004797,0.618876,-0.345056,...,-0.031831,0.348612,-0.354943,0.486604,0.151455,-0.517390,0.059857,0.228941,-0.356924,TCGA
4,TCGA-4H-AAAK,-0.080052,0.130887,-0.030450,0.350385,0.060477,-0.088916,-0.318143,0.179307,-0.577375,...,0.561928,0.106048,0.508212,-0.421759,0.367758,0.417073,0.544952,-0.148332,-0.206994,TCGA

## Allign clinical records with EMBEDINGS(TGCA)

In [8]:
# Find common patients
common_tcga = set(tcga_emb["patient_id"]).intersection(set(survival.index))

print("Common patients:", len(common_tcga))

# Subset embeddings
tcga_emb_aligned = tcga_emb[tcga_emb["patient_id"].isin(common_tcga)].copy()

# Subset survival
tcga_surv_aligned = survival.loc[list(common_tcga)].copy()

print("Embeddings after alignment:", tcga_emb_aligned.shape)
print("Survival after alignment:", tcga_surv_aligned.shape)

Common patients: 1075
Embeddings after alignment: (1075, 26)
Survival after alignment: (1075, 2)

In [9]:
import numpy as np

# Sort both by patient_id to ensure exact alignment
tcga_emb_aligned = tcga_emb_aligned.sort_values("patient_id")
tcga_surv_aligned = tcga_surv_aligned.loc[tcga_emb_aligned["patient_id"]]

# Prepare features
X = tcga_emb_aligned[[f"emb_{i}" for i in range(24)]].values

# Prepare labels
y = tcga_surv_aligned["OS"].values

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Deaths:", np.sum(y))

X shape: (1075, 24)
y shape: (1075,)
Deaths: 147

# METABRICK CLINICAL SURVIVAL DATA

In [10]:
import pandas as pd

meta_clin = pd.read_csv("brca_metabric_clinical_data.tsv", sep="\t")

print("Shape:", meta_clin.shape)
print("\nColumns:\n", meta_clin.columns)
meta_clin.head()

Shape: (2509, 39)

Columns:
 Index(['Study ID', 'Patient ID', 'Sample ID', 'Age at Diagnosis',
       'Type of Breast Surgery', 'Cancer Type', 'Cancer Type Detailed',
       'Cellularity', 'Chemotherapy', 'Pam50 + Claudin-low subtype', 'Cohort',
       'ER status measured by IHC', 'ER Status', 'Neoplasm Histologic Grade',
       'HER2 status measured by SNP6', 'HER2 Status',
       'Tumor Other Histologic Subtype', 'Hormone Therapy',
       'Inferred Menopausal State', 'Integrative Cluster',
       'Primary Tumor Laterality', 'Lymph nodes examined positive',
       'Mutation Count', 'Nottingham prognostic index', 'Oncotree Code',
       'Overall Survival (Months)', 'Overall Survival Status', 'PR Status',
       'Radio Therapy', 'Relapse Free Status (Months)', 'Relapse Free Status',
       'Number of Samples Per Patient', 'Sample Type', 'Sex',
       '3-Gene classifier subtype', 'TMB (nonsynonymous)', 'Tumor Size',
       'Tumor Stage', 'Patient's Vital Status'],
      dtype='object')

,Study ID,Patient ID,Sample ID,Age at Diagnosis,Type of Breast Surgery,Cancer Type,Cancer Type Detailed,Cellularity,Chemotherapy,Pam50 + Claudin-low subtype,...,Relapse Free Status (Months),Relapse Free Status,Number of Samples Per Patient,Sample Type,Sex,3-Gene classifier subtype,TMB (nonsynonymous),Tumor Size,Tumor Stage,Patient's Vital Status
0,brca_metabric,MB-0000,MB-0000,75.65,MASTECTOMY,Breast Cancer,Breast Invasive Ductal Carcinoma,NaN,NO,claudin-low,...,140.500000,0:Not Recurred,1,Primary,Female,ER-/HER2-,0.000000,22.0,2.0,Living
1,brca_metabric,MB-0002,MB-0002,43.19,BREAST CONSERVING,Breast Cancer,Breast Invasive Ductal Carcinoma,High,NO,LumA,...,84.633333,0:Not Recurred,1,Primary,Female,ER+/HER2- High Prolif,2.615035,10.0,1.0,Living
2,brca_metabric,MB-0005,MB-0005,48.87,MASTECTOMY,Breast Cancer,Breast Invasive Ductal Carcinoma,High,YES,LumB,...,153.300000,1:Recurred,1,Primary,Female,NaN,2.615035,15.0,2.0,Died of Disease
3,brca_metabric,MB-0006,MB-0006,47.68,MASTECTOMY,Breast Cancer,Breast Mixed Ductal and Lobular Carcinoma,Moderate,YES,LumB,...,164.933333,0:Not Recurred,1,Primary,Female,NaN,1.307518,25.0,2.0,Living
4,brca_metabric,MB-0008,MB-0008,76.97,MASTECTOMY,Breast Cancer,Breast Mixed Ductal and Lobular Carcinoma,High,YES,LumB,...,18.800000,1:Recurred,1,Primary,Female,ER+/HER2- High Prolif,2.615035,40.0,2.0,Died of Disease

In [11]:
meta_surv = meta_clin[[
    "Patient ID",
    "Overall Survival (Months)",
    "Overall Survival Status"
]].copy()

meta_surv.head()

  Patient ID  Overall Survival (Months) Overall Survival Status
0    MB-0000                 140.500000                0:LIVING
1    MB-0002                  84.633333                0:LIVING
2    MB-0005                 163.700000              1:DECEASED
3    MB-0006                 164.933333                0:LIVING
4    MB-0008                  41.366667              1:DECEASED

In [12]:
meta_surv["Overall Survival Status"].value_counts(dropna=False)

Overall Survival Status
1:DECEASED    1144
0:LIVING       837
NaN            528
Name: count, dtype: int64

In [13]:
# Drop rows with missing survival info
meta_surv = meta_clin.dropna(subset=[
    "Overall Survival Status",
    "Overall Survival (Months)"
]).copy()

# Extract numeric OS (0/1)
meta_surv["OS"] = (
    meta_surv["Overall Survival Status"]
    .str.split(":")
    .str[0]
    .astype(int)
)

# Rename columns
meta_surv = meta_surv.rename(columns={
    "Patient ID": "patient_id",
    "Overall Survival (Months)": "OS.time"
})

# Keep only required columns
meta_surv = meta_surv[["patient_id", "OS", "OS.time"]]

print("Cleaned METABRIC survival shape:", meta_surv.shape)
meta_surv.head()

Cleaned METABRIC survival shape: (1981, 3)

  patient_id  OS     OS.time
0    MB-0000   0  140.500000
1    MB-0002   0   84.633333
2    MB-0005   1  163.700000
3    MB-0006   0  164.933333
4    MB-0008   1   41.366667

## metabrick embeddings and alignment

In [14]:
# Load METABRIC embeddings if not already loaded
meta_emb = pd.read_csv("metabric_embeddings.csv")

print("METABRIC embeddings shape:", meta_emb.shape)

# Find common patients
common_meta = set(meta_emb["patient_id"]).intersection(set(meta_surv["patient_id"]))

print("Common METABRIC patients:", len(common_meta))

# Subset both
meta_emb_aligned = meta_emb[meta_emb["patient_id"].isin(common_meta)].copy()
meta_surv_aligned = meta_surv[meta_surv["patient_id"].isin(common_meta)].copy()

print("Embeddings after alignment:", meta_emb_aligned.shape)
print("Survival after alignment:", meta_surv_aligned.shape)

METABRIC embeddings shape: (1378, 26)
Common METABRIC patients: 0
Embeddings after alignment: (0, 26)
Survival after alignment: (0, 3)

In [15]:
print("Embedding IDs example:")
print(meta_emb["patient_id"].head())

print("\nSurvival IDs example:")
print(meta_surv["patient_id"].head())

Embedding IDs example:
0    MB.2747
1    MB.0384
2    MB.6103
3    MB.7254
4    MB.4709
Name: patient_id, dtype: object

Survival IDs example:
0    MB-0000
1    MB-0002
2    MB-0005
3    MB-0006
4    MB-0008
Name: patient_id, dtype: object

In [16]:
meta_emb["patient_id"].unique()[:20]

array(['MB.2747', 'MB.0384', 'MB.6103', 'MB.7254', 'MB.4709', 'MB.5062',
       'MB.4350', 'MB.4757', 'MB.2556', 'MB.4675', 'MB.3459', 'MB.6113',
       'MB.3412', 'MB.3838', 'MB.2951', 'MB.4739', 'MB.5105', 'MB.4968',
       'MB.5251', 'MB.0380'], dtype=object)

In [17]:
# Replace dot with hyphen
meta_emb["patient_id"] = meta_emb["patient_id"].str.replace(".", "-", regex=False)

# Now check intersection again
common_meta = set(meta_emb["patient_id"]).intersection(set(meta_surv["patient_id"]))

print("Common METABRIC patients after fix:", len(common_meta))

Common METABRIC patients after fix: 1378

In [18]:
# Ensure IDs are fixed
meta_emb["patient_id"] = meta_emb["patient_id"].str.replace(".", "-", regex=False)

# Align datasets
common_meta = set(meta_emb["patient_id"]).intersection(set(meta_surv["patient_id"]))

meta_emb_aligned = meta_emb[meta_emb["patient_id"].isin(common_meta)].copy()
meta_surv_aligned = meta_surv[meta_surv["patient_id"].isin(common_meta)].copy()

print("METABRIC embeddings:", meta_emb_aligned.shape)
print("METABRIC survival:", meta_surv_aligned.shape)

METABRIC embeddings: (1378, 26)
METABRIC survival: (1378, 3)